# Generated by Django 5.2.17 on 2026-09-25 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FanGearLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switchedAt', models.DateTimeField(verbose_name='切换时刻')),
                ('gear', models.PositiveSmallIntegerField(choices=[(1, '1 档'), (2, '2 档'), (3, '3 档'), (4, '4 档'), (5, '5 档')], verbose_name='档位')),
                ('operator', models.CharField(max_length=80, verbose_name='操作人')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gear_logs', to='gardens.garden', verbose_name='茶园')),
            ],
            options={
                'verbose_name': '风机档位志',
                'verbose_name_plural': '风机档位志',
                'ordering': ['-switchedAt', '-id'],
                'constraints': [models.UniqueConstraint(fields=('garden', 'switchedAt'), name='uniq_gear_log_minute_per_garden')],
            },
        ),
    ]
